workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - check
  - update

default:
  image: "nixos/nix:latest"

check-jobs:
  stage: check
  script:
    - nix --extra-experimental-features 'flakes nix-command' flake check

update-jobs:
  stage: update
  script:
    - nix --extra-experimental-features 'flakes nix-command' flake update

